### ISSUE TITLE
Full screen icons not working

### ISSUE THREAD

**Issue by geealbers** [thegetty/grj-19#41]
Full screen icons are not working in the modal lightbox. They've been temporarily hidden with CSS until they can be fixed.

```css
.q-lightbox-ui__fullscreen-button {
  display: none;
}
```
